services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: nois2_192_server
    ports:
      - "19000:8000"
    env_file:
      - .env.prod

  background:
    build:
      context: .
      dockerfile: Dockerfile.background
    container_name: nois2_192_background
    env_file:
      - .env.prod
